#!/bin/sh

npm install -g @angular/cli
npm install -g @microsoft/generator-sharepoint
npm install -g azure-cli
npm install -g browserify
npm install -g eslint
npm install -g express
npm install -g generator-generator
npm install -g grunt-cli
npm install -g gulp
npm install -g h2m
npm install -g http-server
npm install -g istanbul
npm install -g jshint
npm install -g jspm
npm install -g karma-cli
npm install -g mocha
npm install -g nodemon
npm install -g nodetree
npm install -g phantomjs
npm install -g source-map-explorer
npm install -g sql-cli
npm install -g superstatic
npm install -g systemjs
npm install -g tslint
npm install -g typedoc
npm install -g typescript
npm install -g typings
npm install -g uglify-js
npm install -g webpack
npm install -g yo