#!/bin/zsh

code --install-extension 1password.op-vscode
code --install-extension aaron-bond.better-comments
code --install-extension acrolinx.vscode-sidebar
code --install-extension adobe.extendscript-debug
code --install-extension alefragnani.bookmarks
code --install-extension anthropic.claude-code
code --install-extension azurite.azurite
code --install-extension blackmist.linkcheckmd
code --install-extension bradlc.vscode-tailwindcss
code --install-extension budparr.language-hugo-vscode
code --install-extension cschlosser.doxdocgen
code --install-extension davidanson.vscode-markdownlint
code --install-extension docsmsft.docs-article-templates
code --install-extension docsmsft.docs-authoring-pack
code --install-extension docsmsft.docs-build
code --install-extension docsmsft.docs-images
code --install-extension docsmsft.docs-linting
code --install-extension docsmsft.docs-markdown
code --install-extension docsmsft.docs-metadata
code --install-extension docsmsft.docs-preview
code --install-extension docsmsft.docs-scaffolding
code --install-extension docsmsft.docs-visual-areas
code --install-extension docsmsft.docs-yaml
code --install-extension eamodio.gitlens
code --install-extension eliostruyf.vscode-demo-time
code --install-extension esbenp.prettier-vscode
code --install-extension fivethree.vscode-hugo-snippets
code --install-extension formulahendry.auto-rename-tag
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension humao.rest-client
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension jock.svg
code --install-extension jsynowiec.vscode-insertdatestring
code --install-extension learningengineeringoperations.learn-training-ai-assistant
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-azure-github-copilot
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-bicep
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-graph.kiota
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.wordcount
code --install-extension oouo-diogo-perdigao.docthis
code --install-extension patbenatar.advanced-new-file
code --install-extension postman.postman-for-vscode
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension sdras.night-owl
code --install-extension shardulm94.trailing-spaces
code --install-extension sharepointembedded.ms-sharepoint-embedded-vscode-extension
code --install-extension shuworks.vscode-table-formatter
code --install-extension sissel.shopify-liquid
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tailwindlabs.tailwindcss-vscode-theme
code --install-extension teamsdevapp.ms-teams-vscode-extension
code --install-extension teamsdevapp.vscode-adaptive-cards
code --install-extension timonwong.shellcheck
code --install-extension twxs.cmake
code --install-extension typespec.typespec-vscode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wallabyjs.wallaby-vscode
code --install-extension wesbos.theme-cobalt2
code --install-extension zhouronghui.propertylist
