#!/bin/sh

Acrolinx.vscode-sidebar
blackmist.LinkCheckMD
bradlc.vscode-tailwindcss
CoenraadS.bracket-pair-colorizer
DavidAnson.vscode-markdownlint
docsmsft.docs-article-templates
docsmsft.docs-authoring-pack
docsmsft.docs-build
docsmsft.docs-images
docsmsft.docs-linting
docsmsft.docs-markdown
docsmsft.docs-metadata
docsmsft.docs-preview
docsmsft.docs-scaffolding
docsmsft.docs-yaml
fivethree.vscode-hugo-snippets
jsynowiec.vscode-insertdatestring
ms-vscode.wordcount
msjsdiag.debugger-for-chrome
redhat.vscode-yaml
sdras.night-owl
shardulm94.trailing-spaces
shuworks.vscode-table-formatter
streetsidesoftware.code-spell-checker
vscode-icons-team.vscode-icons
WallabyJs.wallaby-vscode
wayou.vscode-todo-highlight