#!/bin/sh
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension DotJoshJohnson.xml
code --install-extension EditorConfig.EditorConfig
code --install-extension HookyQR.beautify
code --install-extension PKief.material-icon-theme
code --install-extension PeterJausovec.vscode-docker
code --install-extension Shan.code-settings-sync
code --install-extension Tyriar.theme-sapphire
code --install-extension WallabyJs.quokka-vscode
code --install-extension Zignd.html-css-class-completion
code --install-extension abusaidm.html-snippets
code --install-extension adamhartford.vscode-base64
code --install-extension akmittal.hugofy
code --install-extension anseki.vscode-color
code --install-extension christian-kohler.npm-intellisense
code --install-extension dbaeumer.jshint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension felipecaputo.git-project-manager
code --install-extension idleberg.emoji-code
code --install-extension joelday.docthis
code --install-extension johnpapa.Angular1
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.azure-functions-tools
code --install-extension jvandyke.vscode-circleci
code --install-extension liuji-jim.vue
code --install-extension lukehoban.Go
code --install-extension mdickin.markdown-shortcuts
code --install-extension minhthai.vscode-todo-parser
code --install-extension mitchdenny.ecdc
code --install-extension mkaufman.HTMLHint
code --install-extension ms-mssql.mssql
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.PowerShell
code --install-extension ms-vscode.Theme-MarkdownKit
code --install-extension ms-vsts.team
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natewallace.angular2-inline
code --install-extension neilding.language-liquid
code --install-extension raymondcamden.htmlescape-vscode-extension
code --install-extension robertohuertasm.vscode-icons
code --install-extension ronnidc.nunjucks
code --install-extension seanmcbreen.MDTools
code --install-extension shuworks.vscode-table-formatter
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension wix.vscode-import-cost